hmrc/lisa-api

resources/public/api/conf/1.0/application.raml
resources/public/api/conf/1.0/schemas/LISAManager.get.schema.json

Changes to:
resources/public/api/conf/1.0/application.raml
resources/public/api/conf/1.0/schemas/LISAManager.get.schema.json
Raghu to check changes before merging.

Content changes

---

app/uk/gov/hmrc/lisaapi/controllers/JsonFormats.scala
app/uk/gov/hmrc/lisaapi/models/CreateLisaInvestorRequest.scala
test/unit/models/CreateLisaInvestorRequest.scala

Includes Json validation rules for deserialization.

Added a model for Create LISA Investor requests

---

app/uk/gov/hmrc/lisaapi/connectors/DesConnector.scala
app/uk/gov/hmrc/lisaapi/controllers/InvestorController.scala
app/uk/gov/hmrc/lisaapi/controllers/JsonFormats.scala
app/uk/gov/hmrc/lisaapi/models/ApiResponse.scala
app/uk/gov/hmrc/lisaapi/models/ApiResponseData.scala
app/uk/gov/hmrc/lisaapi/models/CreateLisaInvestorResponse.scala
app/uk/gov/hmrc/lisaapi/models/des/DesCreateInvestorResponse.scala
app/uk/gov/hmrc/lisaapi/services/InvestorService.scala
conf/prod.routes
test/unit/connectors/DesConnectorSpec.scala
test/unit/controllers/InvestorControllerSpec.scala
test/unit/services/InvestorServiceSpec.scala

Now handle all of the expected responses from DES and filter these through all the application layers back to the end user.

Handle expected DES responses

---

conf/application.conf
conf/dev.routes

Create Dev routes file

---

app/uk/gov/hmrc/lisaapi/connectors/DesConnector.scala
app/uk/gov/hmrc/lisaapi/controllers/ErrorResponses.scala
app/uk/gov/hmrc/lisaapi/controllers/InvestorController.scala
app/uk/gov/hmrc/lisaapi/controllers/LisaController.scala
app/uk/gov/hmrc/lisaapi/controllers/package.scala

Error responses returned by the controller now match the schema definitions.
Still to consider (separate story): How do we want to return the validation errors?

Amended error responses

---

conf/dev.routes

Requires all manager IDs conform to the agreed regex

Added regex rule for manager IDs

---

test/unit/controllers/LisaControllerSpec.scala

Added a Unit Test for checking Json read Exceptions get caught
- The only untested piece of code in our base LisaController

Test json read exceptions

---

app/uk/gov/hmrc/lisaapi/connectors/DesConnector.scala
app/uk/gov/hmrc/lisaapi/controllers/AccountController.scala
app/uk/gov/hmrc/lisaapi/controllers/ErrorResponses.scala
app/uk/gov/hmrc/lisaapi/controllers/LisaController.scala
app/uk/gov/hmrc/lisaapi/services/AccountService.scala
test/unit/connectors/DesConnectorSpec.scala
test/unit/controllers/AccountControllerSpec.scala
test/unit/services/AccountServiceSpec.scala

API functionality for the Transfer Account endpoint

LISA-121 Transfer LISA Account

---

app/uk/gov/hmrc/lisaapi/controllers/JsonFormats.scala

* AccountID regex added
* Nino regex updated
* Name regex updated

Updated regular expressions for various json payload validations

---

conf/dev.routes

Z ref should contain 4 or 6 numbers, not between 4 and 6

Updated zref regex in routes

---

app/uk/gov/hmrc/lisaapi/connectors/DesConnector.scala
app/uk/gov/hmrc/lisaapi/controllers/BonusPaymentController.scala
app/uk/gov/hmrc/lisaapi/controllers/JsonFormats.scala
app/uk/gov/hmrc/lisaapi/controllers/LisaController.scala
app/uk/gov/hmrc/lisaapi/models/ApiResponseData.scala
app/uk/gov/hmrc/lisaapi/models/RequestBonusPaymentResponse.scala
app/uk/gov/hmrc/lisaapi/services/BonusPaymentService.scala
conf/dev.routes
test/unit/connectors/DesConnectorSpec.scala
test/unit/controllers/BonusPaymentControllerSpec.scala
test/unit/services/BonusPaymentServiceSpec.scala

Started moving in a different direction given we now know DES will return
a response identical to the response we are to return.
We'll likely want to do a refactor in the near future, but I've maintained
backwards compatibility for the time being.

LISA-507 Bonus Payments Service & Controller

---

app/uk/gov/hmrc/lisaapi/controllers/BonusPaymentController.scala
app/uk/gov/hmrc/lisaapi/controllers/ErrorResponses.scala
app/uk/gov/hmrc/lisaapi/controllers/JsonFormats.scala
app/uk/gov/hmrc/lisaapi/models/RequestBonusPaymentRequest.scala
app/uk/gov/hmrc/lisaapi/models/ResorceModel.scala
test/unit/connectors/DesConnectorSpec.scala
test/unit/controllers/BonusPaymentControllerSpec.scala
test/unit/models/RequestBonusPaymentRequestSpec.scala
test/unit/services/BonusPaymentServiceSpec.scala

* Added LIFE_EVENT_NOT_PROVIDED error on request bonus payment API
* Updated some bonus payment request fields to be optional

Bonus payment amends 548

---

app/uk/gov/hmrc/lisaapi/controllers/JsonFormats.scala
app/uk/gov/hmrc/lisaapi/models/CreateLisaInvestorRequest.scala
test/unit/controllers/InvestorControllerSpec.scala
test/unit/models/CreateLisaInvestorRequestSpec.scala

Case Classes
Json Formats
Unit Tests

Change DoB to dateOfBirth in

---

resources/public/api/conf/1.0/testdata/bonus-payment.md
resources/public/api/conf/1.0/testdata/close-account.md
resources/public/api/conf/1.0/testdata/create-account.md
resources/public/api/conf/1.0/testdata/life-event.md
resources/public/api/conf/1.0/testdata/lisa-create-investor.md

Added on behalf of Siva Prasad

LISA-590 Updated test data documentation

---

app/uk/gov/hmrc/lisaapi/controllers/JsonFormats.scala
app/uk/gov/hmrc/lisaapi/models/CreateLisaAccountRequest.scala
test/unit/connectors/DesConnectorSpec.scala
test/unit/controllers/AccountControllerSpec.scala
test/unit/models/CreateLisaAccountRequestSpec.scala
test/unit/services/AccountServiceSpec.scala

jsonformats
models
model tests
Connector tests
Controller tests
service tests

Remove LisaReference models for Account

---

resources/public/api/conf/1.0/testdata/create-account.md

Noticed the scenario text was incorrect. Amended.

LISA-597 Update API Spec (2)

---

app/uk/gov/hmrc/lisaapi/controllers/ErrorResponses.scala
app/uk/gov/hmrc/lisaapi/controllers/LisaController.scala
test/unit/controllers/LisaControllerSpec.scala

Add new test condition for failed auth - LisacontrollerSpec

Add Error handling for UnAuthorized - ErrorResponses, LisaController

---

app/uk/gov/hmrc/lisaapi/config/microserviceGlobal.scala
app/uk/gov/hmrc/lisaapi/config/microserviceWiring.scala
app/uk/gov/hmrc/lisaapi/controllers/AccountController.scala
app/uk/gov/hmrc/lisaapi/controllers/BonusPaymentController.scala
app/uk/gov/hmrc/lisaapi/controllers/DiscoverController.scala
app/uk/gov/hmrc/lisaapi/controllers/ErrorResponses.scala
app/uk/gov/hmrc/lisaapi/controllers/InvestorController.scala
app/uk/gov/hmrc/lisaapi/controllers/LifeEventController.scala
app/uk/gov/hmrc/lisaapi/controllers/LisaController.scala
conf/application.conf
project/MicroServiceBuild.scala
resources/public/api/conf/1.0/testdata/bonus-payment.md
resources/public/api/conf/1.0/testdata/close-account.md
resources/public/api/conf/1.0/testdata/life-event.md
resources/public/api/conf/1.0/testdata/lisa-create-investor.md
test/unit/controllers/AccountControllerSpec.scala
test/unit/controllers/BonusPaymentControllerSpec.scala
test/unit/controllers/InvestorControllerSpec.scala
test/unit/controllers/LifeEventControllerSpec.scala
test/unit/controllers/LisaControllerSpec.scala

Revert "Lisa 117"

---

app/uk/gov/hmrc/lisaapi/controllers/AccountController.scala
app/uk/gov/hmrc/lisaapi/controllers/InvestorController.scala
app/uk/gov/hmrc/lisaapi/controllers/LisaController.scala
app/uk/gov/hmrc/lisaapi/services/AuditService.scala
conf/application.conf
test/unit/controllers/AccountControllerSpec.scala
test/unit/controllers/BonusPaymentControllerSpec.scala
test/unit/controllers/DiscoverControllerSpec.scala
test/unit/controllers/InvestorControllerSpec.scala
test/unit/controllers/LifeEventControllerSpec.scala
test/unit/controllers/LisaControllerSpec.scala
test/unit/services/AuditServiceSpec.scala

* Audit Service Created
* Integrated with Investor Controller
* Audit events added for InvestorCreated and InvestorNotCreated scenarios
* Lots of Unit Tests and Refactoring

Create Investor Auditing

---

test/unit/controllers/AccountControllerSpec.scala
test/unit/controllers/BonusPaymentControllerSpec.scala
test/unit/controllers/InvestorControllerSpec.scala

A number of our auditing unit tests are failing on the CI server.
I suspect it may be that the auditing verification is being done before the controller request has completed.
Made the tests synchronous so that the verification can only be done once the request has completed.

LISA-713 Fix failing unit tests

---

project/MicroServiceBuild.scala

Change as required for LISA-619 (Update microservice domain names)

Updated microservice bootstrap

---

app/uk/gov/hmrc/lisaapi/controllers/InvestorController.scala
test/unit/controllers/InvestorControllerSpec.scala

Date of Birth data added to:
* investorCreated
* investorNotCreated

LISA-749 Added dateOfBirth to create investor audit events

---

resources/public/api/conf/1.0/examples/LifeEvent.post.response.json
resources/public/api/conf/1.0/testdata/life-event.md

LISA-774 Update example lifeEventId response to be 10 digits long

---

app/uk/gov/hmrc/lisaapi/connectors/DesConnector.scala
app/uk/gov/hmrc/lisaapi/controllers/ErrorResponses.scala
app/uk/gov/hmrc/lisaapi/controllers/InvestorController.scala
app/uk/gov/hmrc/lisaapi/models/CreateLisaInvestorResponse.scala
app/uk/gov/hmrc/lisaapi/services/InvestorService.scala
test/unit/connectors/DesConnectorSpec.scala
test/unit/controllers/InvestorControllerSpec.scala
test/unit/services/InvestorServiceSpec.scala

Now expects back a "investorID" as per latest DES schema

LISA-783 Updated INVESTOR_ALREADY_EXISTS response handling

---

resources/public/api/conf/1.0/testdata/close-account.md

Update close account test data http status from 201 to 200

---

app/uk/gov/hmrc/lisaapi/controllers/JsonFormats.scala
resources/public/api/conf/1.0/schemas/LifeEvent.post.schema.json
resources/public/api/conf/1.0/testdata/life-event.md

Removed House Purchase option from Report a Life Event

---

resources/public/api/conf/1.0/examples/LISAAccount.close.post.json
resources/public/api/conf/1.0/examples/LISAInvestor.post.json
resources/public/api/conf/1.0/schemas/LISAAccount.post.schema.json
resources/public/api/conf/1.0/schemas/LISAInvestor.post.schema.json
resources/public/api/conf/1.0/schemas/LifeEvent.post.schema.json

Ensuring all date examples are accurate for their associated business rules. Still further work to do but it's a start.

LISA-607 Documentation updates

---

resources/public/api/conf/1.0/documentation/LifeEvent

Removed reference of house purchase from life event description

---

resources/public/api/conf/1.0/application.raml
resources/public/api/conf/1.0/testdata/bonus-payment.md
resources/public/api/conf/1.0/testdata/close-account.md
resources/public/api/conf/1.0/testdata/create-account.md
resources/public/api/conf/1.0/testdata/life-event.md
resources/public/api/conf/1.0/testdata/lisa-create-investor.md

Documentation updates to:
* Increase consistency, readability and simplicity across all test data
* Ensure test data dates pass date validation rules
* Ensure test data scenarios are in the same order as the documented API responses

Amended API documentation

---

resources/public/api/conf/1.0/testdata/bonus-payment.md

Small mistake in last merge. Fixed.

Documentation fix for Bonus Payments

---

app/uk/gov/hmrc/lisaapi/utils/ErrorConverter.scala
test/unit/utils/ErrorConverterSpec.scala

Updated error messages as per latest content review. Added new message specifically for invalid monetary amounts.

LISA-841: Updated error messages

---

app/uk/gov/hmrc/lisaapi/controllers/AccountController.scala
resources/public/api/conf/1.0/testdata/bonus-payment.md
resources/public/api/conf/1.0/testdata/close-account.md
resources/public/api/conf/1.0/testdata/create-account.md
resources/public/api/conf/1.0/testdata/life-event.md
resources/public/api/conf/1.0/testdata/lisa-create-investor.md

Test data documentation now shows the new errors coming back for Bad Requests.
Also fixed an issue where the Account requests weren't returning the validation errors.

LISA-841: Updated all test data documentation

---

app/uk/gov/hmrc/lisaapi/models/package.scala
app/uk/gov/hmrc/lisaapi/utils/ErrorConverter.scala
test/unit/models/JsonSpec.scala

Can now catch and correctly handle:
* Numeric values sent as strings i.e. "1.00"
* Non numeric values i.e. "X"

LISA-904: Updated monetary reads

---

resources/public/api/conf/1.0/testdata/bonus-payment.md

Updated an incorrect z ref in the bonus payment api test data

LISA-913: Fix for test data

---

app/uk/gov/hmrc/lisaapi/controllers/HelperController.scala
conf/release2.routes
test/unit/controllers/HelperControllerSpec.scala

Report a Life Event and Request a Bonus Payment to return Not Implemented until Release 3

LISA-1126: Release 2 routes

---

resources/public/api/conf/1.0/documentation/testing-approach.md
resources/public/api/conf/1.0/testdata/bonus-payment.md
resources/public/api/conf/1.0/testdata/close-account.md
resources/public/api/conf/1.0/testdata/create-account.md
resources/public/api/conf/1.0/testdata/discover-endpoints.md
resources/public/api/conf/1.0/testdata/life-event.md
resources/public/api/conf/1.0/testdata/lisa-create-investor.md

fixing Test data in external test

Et api doc update

---

app/uk/gov/hmrc/lisaapi/controllers/BonusPaymentController.scala
app/uk/gov/hmrc/lisaapi/controllers/ErrorResponses.scala
app/uk/gov/hmrc/lisaapi/utils/BonusPaymentValidator.scala
test/resources/json/request.valid.bonus-payment.json
test/resources/json/request.valid.bonus-payment.min.json
test/unit/controllers/BonusPaymentControllerSpec.scala
test/unit/utils/BonusPaymentValidatorSpec.scala

Monetary values now validated against our pre-defined rules.

LISA-802: Added business rule validation to Bonus Payment API

---

resources/public/api/conf/1.0/application.raml
resources/public/api/conf/1.0/testdata/bonus-payment.md

* Updated bonus payment raml to add in the generic 403 response
* Added test data example of a request failing the new business rule validation
* Fixed an issue in the test data md where opened <a> tags weren't being closed

LISA-802: Updated test data and raml

---

app/uk/gov/hmrc/lisaapi/controllers/LisaController.scala

Added catch all so that any authorisation exception will result in an unauthorised response.

LISA-1163: Updated authorisation error handling

---

resources/public/api/conf/1.0/application.raml
resources/public/api/conf/1.0/testdata/bonus-payment-get.md

Now includes test data and scenarios

LISA-1316: Updated spec for bonus payment GET

---

project/MicroServiceBuild.scala
test/unit/config/RegisterInServiceLocatorSpec.scala
test/unit/connectors/ServiceLocatorConnectorSpec.scala
test/unit/controllers/ErrorResponseSpec.scala
test/unit/models/ModelSpec.scala

* Removed hmrctest dependency
* Updated any of the UnitSpec references to use PlaySpec
Also bumped authclient version by a minor release. All acceptance and unit tests continue to pass as before.

LISA-1536: Removed reference to hmrctest

---

app/uk/gov/hmrc/lisaapi/controllers/DiscoverController.scala
resources/public/api/conf/1.0/examples/LISAManager.get.json
resources/public/api/conf/1.0/schemas/LISAManager.get.schema.json
test/unit/controllers/DiscoverControllerSpec.scala

* Updated the controller's response to match the example from the API spec.
* Amended 'Account' to be 'account' as per content guidelines.
* Formatted JSON to make it read a little easier.

LISA-1539: Updated discover available endpoints

---

resources/public/api/conf/1.0/application.raml

Added full stop to the reinstate account description

LISA-1624: Updated reinstate account raml

---

resources/public/api/conf/1.0/application.raml
resources/public/api/conf/1.0/testdata/subscription-update.md

The business rules have been updated and this is no longer a valid use case.

LISA-1634: Removed UPDATED_AND_ACCOUNT_OPENED

---

resources/public/api/conf/1.0/schemas/LISAAccount.get.schema.json

* Updated description of accountStatus and subscriptionStatus following review with Andy.
* Made accountStatus a required field in the response
All other changes are whitespace from autoformatting.

LISA-1390: Updated field descriptions for GET account

---

resources/public/api/conf/1.0/application.raml

included POST schema , as not sure if GET schema has been updated with content review.

LISA-1727: included schema for response

---

app/uk/gov/hmrc/lisaapi/connectors/DesConnector.scala
app/uk/gov/hmrc/lisaapi/models/des/DesResponse.scala
app/uk/gov/hmrc/lisaapi/services/BonusPaymentService.scala
app/uk/gov/hmrc/lisaapi/services/TransactionService.scala
resources/public/api/conf/1.0/testdata/bonus-payment-get.md
test/resources/json/request.valid.bonus-payment-response.json
test/unit/connectors/DesConnectorSpec.scala
test/unit/services/BonusPaymentServiceSpec.scala
test/unit/services/TransactionServiceSpec.scala

The response now comes in a different format with a slight different transaction not found error.
Updated our service and JSON reads to compensate.

LISA-1729: Updated GET bonus payment response handling

---

app/uk/gov/hmrc/lisaapi/connectors/DesConnector.scala

Updated the backend URLs for two of our endpoints as per latest specs.

LISA-1772: Updated transaction URLs

---

resources/public/api/conf/1.0/schemas/BonusPaymentRequest.post.schema.json

LISA-2002: Content updates

---

app/uk/gov/hmrc/lisaapi/controllers/package.scala
app/uk/gov/hmrc/lisaapi/models/AnnualReturn.scala
resources/public/api/conf/2.0/schemas/AnnualReturn.post.schema.json
test/unit/models/AnnualReturnSpec.scala

You are now unable to create an annual return for the current tax year

LISA-2246: Added more validation to annual returns

---

app/uk/gov/hmrc/lisaapi/models/AnnualReturn.scala
test/unit/models/ReportLifeEventRequestSpec.scala

Now is converted from int to string before being sent on

Updated taxYear json serialisation

---

resources/public/api/conf/2.0/schemas/LISATransaction.get.response.schema.json

Documentation change only - already existed in code.

LISA-2309: Added automaticRecoveryAmount to GET Bonus Claim

---

.github/PULL_REQUEST_TEMPLATE.md
.gitignore
app/uk/gov/hmrc/lisaapi/controllers/Responses.scala
build.sbt
project/AppDependencies.scala
project/plugins.sbt
resources/public/api/conf/2.0/application.raml
resources/public/api/conf/2.0/testdata/withdrawal-charge.md
test/unit/controllers/WithdrawalControllerSpec.scala

Changing the error message. Cannot go live before 4pm Tuesday 23rd!
Link to lisa-api-tests PR for this: https://github.com/hmrc/lisa-api-tests/pull/95
- Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?
- Have you done a visual check of the changes?
- Is there any still commented or unused code? Lingering printlns?
- Have things been implemented in a complicated way?
- Are the test still over the coverage threshold?
- Does the compiler throw a lot of warnings? 
- Have methods and tests been named clearly?
- Were there any changes in the config? Do changes need to be made in app-config-???

DDCE-577: Updating WITHDRAWAL_REPORTING_ERROR message

---

resources/public/api/conf/2.0/application.raml

Fixed a break between two lines which was causing the documentation to fail publication on QA.
- Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?
- Have you done a visual check of the changes?
- Is there any still commented or unused code? Lingering printlns?
- Have things been implemented in a complicated way?
- Are the test still over the coverage threshold?
- Does the compiler throw a lot of warnings? 
- Have methods and tests been named clearly?
- Were there any changes in the config? Do changes need to be made in app-config-???

DDCE-577: Fixed new line causing publishing failure

---

resources/public/api/conf/1.0/application.raml
resources/public/api/conf/2.0/application.raml

Please include a summary / description of the change and which issue it fixes.  Include any relevant user needs, context or links to other PRs related to this PR (eg. acceptance tests, environment config).

DDCE-1665: shortened raml description

---

resources/public/api/conf/2.0/examples/BonusPaymentRequest.post.json
resources/public/api/conf/2.0/examples/LISATransaction.get.response.1.json
resources/public/api/conf/2.0/testdata/bonus-payment-get.md
resources/public/api/conf/2.0/testdata/bonus-payment.md

Simple .json and .md updates with more accurate example figures.

[EH][DDCE-1772] Updated lisa-api docs (2.0) to include accurate figures

---

project/AppDependencies.scala
project/plugins.sbt

DDCE-2029: Play 2.8 Upgrade

---

app/uk/gov/hmrc/lisaapi/connectors/DesConnector.scala
app/uk/gov/hmrc/lisaapi/models/des/DesGetTransactionResponse.scala
build.sbt
test/unit/connectors/DesConnectorSpec.scala
test/unit/connectors/DesConnectorTestHelper.scala

Improve error handling on LISA Api for 'Unexpected character'

DDCE-2983-Sajad - Improve error handling on LISA Api for 'Unexpected character'

---

app/uk/gov/hmrc/lisaapi/views/definition.scala.txt
conf/logback.xml
project/plugins.sbt

DDCE-6058 - Removing scopes from API definition

DDCE-6058 - Removing scope from API definition
