app/uk/gov/hmrc/lisaapi/connectors/DesConnector.scala, app/uk/gov/hmrc/lisaapi/controllers/InvestorController.scala, app/uk/gov/hmrc/lisaapi/controllers/LisaController.scala, app/uk/gov/hmrc/lisaapi/services/InvestorService.scala, conf/application.conf, test/unit/connectors/DesConnectorSpec.scala, test/unit/controllers/InvestorControllerSpec.scala, test/unit/services/InvestorServiceSpec.scala
Very barebones implementation - at the moment will only care about if it receives a 201 response or not and will return either "Created" or "Error".
Have deliberately left out more complex / contextual return types for now, and have left out auditing and metrics for the time being also.
=> Added DES connector

project/MicroService.scala
(dev package gets built by generators from dev.routes)
=> Excluded dev package from coverage reports

conf/dev.routes, conf/prod.routes
I believe /lifetime-isa is the base url of the microservice so we shouldn't have it
in the routes.
=> I think this is why the routes aren't working on QA

test/unit/services/InvestorServiceSpec.scala
At some point, the Investor Already Exists response was amended to include an
investor ID, however the tests were not updated correctly to reflect the new
logic.
The logic in place would suggest that if we get an Investor Already Exists
RDS code, then the data payload should include an investor ID - otherwise we
throw an error.
I've amended the tests to reflect this logic.
=> Updated the Investor Service Spec

app/uk/gov/hmrc/lisaapi/services/AccountService.scala, test/unit/controllers/AccountControllerSpec.scala, test/unit/services/AccountServiceSpec.scala
As we are not yet dealing with account transfers, we should never get the
PREVIOUS_INVESTOR_ACCOUNT_DOES_NOT_EXIST response. Updated the functionality
to reflect this.
=> Updated Create Account endpoint

app/uk/gov/hmrc/lisaapi/controllers/AccountController.scala, test/unit/controllers/AccountControllerSpec.scala
Previous implementation would successfully validate a Create request provided the transferAccount property (if included) was invalid.
=> Caught some edge cases on TRANSFER_ACCOUNT_DATA_PROVIDED

app/uk/gov/hmrc/lisaapi/controllers/JsonFormats.scala, resources/public/api/conf/1.0/examples/BonusPaymentRequest.post.json, resources/public/api/conf/1.0/schemas/BonusPaymentRequest.post.schema.json, resources/public/api/conf/1.0/schemas/LISAAccount.close.post.schema.json, resources/public/api/conf/1.0/schemas/LISAAccount.post.schema.json, resources/public/api/conf/1.0/testdata/bonus-payment.md, resources/public/api/conf/1.0/testdata/close-account.md, resources/public/api/conf/1.0/testdata/lisa-create-investor.md, test/resources/json/request.valid.bonus-payment.json, test/resources/json/request.valid.bonus-payment.min.json, test/unit/connectors/DesConnectorSpec.scala, test/unit/models/RequestBonusPaymentRequestSpec.scala, test/unit/services/AuditServiceSpec.scala, test/unit/services/BonusPaymentServiceSpec.scala
Added validation checks to the dates on the Create/Transfer endpoint to ensure they are not in the future.
Updated API spec to ensure no future dates were being used in the test data examples unless it was a specific example of failing date validation.
Fixed a couple of typos.
=> LISA-607 Date validation on Create/Transfer endpoint

app/uk/gov/hmrc/lisaapi/services/AccountService.scala, test/unit/services/AccountServiceSpec.scala
DES sends us INVESTOR_ACCOUNT_ALREADY_CLOSED rather than
INVESTOR_ACCOUNT_ALREADY_CLOSED_OR_VOID so we need to
handle that...
=> Updated closed response for Create/Transfer

app/uk/gov/hmrc/lisaapi/models/CreateLisaAccountRequest.scala, test/unit/models/CreateLisaAccountRequestSpec.scala
Fixes LISA-903 and LISA-901:
A missing or invalid 'creationReason' on a account creation/transfer request will now return the correct error message.
Had to make the response slightly opinionated as if they were intending a creation request but this seemed the simplest approach as it shares all the same fields as a transfer request, only missing out the transfer object.
=> LISA-903: Bug fix for 'creationReason' field

app/uk/gov/hmrc/lisaapi/utils/BonusPaymentValidator.scala
Having them as two separate rules could cause both rules to fail and the same validation error to display twice.
=> LISA-690: Consolidated periodEndDate rules to avoid duplicate errors

resources/public/api/conf/1.0/testdata/life-event.md
409 Conflict response now contains the lifeEventId of the duplicate event, allowing the user to update their records.
=> LISA-1387: Spec update for report a life event

app/uk/gov/hmrc/lisaapi/controllers/LisaController.scala, app/uk/gov/hmrc/lisaapi/models/package.scala, resources/public/api/conf/1.0/application.raml, resources/public/api/conf/1.0/schemas/LISAAccount.get.schema.json, resources/public/api/conf/1.0/schemas/LISAAccount.post.schema.json, resources/public/api/conf/1.0/schemas/LISAAccount.reinstate.post.schema.json, test/unit/controllers/AccountControllerSpec.scala, test/unit/controllers/BonusPaymentControllerSpec.scala, test/unit/controllers/LifeEventControllerSpec.scala, test/unit/controllers/ReinstateAccountControllerSpec.scala, test/unit/controllers/UpdateFirstSubscriptionDateSpec.scala
Back slashes are now disallowed from accountId and forward slashes are allowed.
=> LISA-1529: Updated accountId regex

app/uk/gov/hmrc/lisaapi/controllers/AccountController.scala, app/uk/gov/hmrc/lisaapi/controllers/BonusPaymentController.scala, app/uk/gov/hmrc/lisaapi/controllers/LifeEventController.scala, app/uk/gov/hmrc/lisaapi/controllers/Responses.scala, app/uk/gov/hmrc/lisaapi/controllers/UpdateSubscriptionController.scala, app/uk/gov/hmrc/lisaapi/controllers/package.scala, app/uk/gov/hmrc/lisaapi/utils/BonusPaymentValidator.scala, resources/public/api/conf/1.0/examples/LISAAccount.post.json, resources/public/api/conf/1.0/examples/LISAAccount.post1.json, resources/public/api/conf/1.0/testdata/bonus-payment.md, resources/public/api/conf/1.0/testdata/close-account.md, resources/public/api/conf/1.0/testdata/create-account.md, resources/public/api/conf/1.0/testdata/life-event.md, resources/public/api/conf/1.0/testdata/subscription-update.md, test/unit/controllers/AccountControllerSpec.scala, test/unit/controllers/BonusPaymentControllerSpec.scala, test/unit/controllers/LifeEventControllerSpec.scala, test/unit/controllers/UpdateFirstSubscriptionDateSpec.scala, test/unit/utils/BonusPaymentValidatorSpec.scala
All dates being passed into the API are now validated to ensure they are not before 6 April 2017.
If they are, a 403 Forbidden will be returned with error messages for any dates that fail validation.
The API docs have been updated to ensure the successful examples use dates after 6 April 2017 and additional failure examples have been added which demonstrate the date validation failing.
In addition, some refactoring has been done on some controllers as the methods were extremely long and had duplication which could be abstracted out.
=> LISA-1663: Added date validation

test/unit/services/TransactionServiceSpec.scala
GET transaction failed as a knock on effect from changes to GET payment
=> Fixed some failing unit tests

resources/public/api/conf/1.0/testdata/bonus-payment-get.md, resources/public/api/conf/1.0/testdata/bonus-payment.md, resources/public/api/conf/1.0/testdata/close-account.md, resources/public/api/conf/1.0/testdata/get-account.md, resources/public/api/conf/1.0/testdata/get-investor-payment.md, resources/public/api/conf/1.0/testdata/life-event.md, resources/public/api/conf/1.0/testdata/reinstate-account.md, resources/public/api/conf/1.0/testdata/subscription-update.md
Using a raw invalid character returns a 404 error from WSO2. If we URL encode the character - in this case changing '=' to '%3D' - then we get the correct 400 Bad Request error from our service.
=> Replaced invalid accountIds in API test examples

app/uk/gov/hmrc/lisaapi/models/GetLisaAccountResponse.scala, resources/public/api/conf/1.0/schemas/LISAAccount.get.schema.json, resources/public/api/conf/1.0/testdata/get-account.md, test/unit/connectors/DesConnectorSpec.scala, test/unit/controllers/AccountControllerSpec.scala, test/unit/services/AccountServiceSpec.scala
* Updated code so if we don't get a subscriptionStatus we return a value of "AVAILABLE"
* Updated API spec so subscriptionStatus is a required field in our response
* Updated test data examples to match changes
=> LISA-1756: Updated subscriptionStatus on GET account

resources/public/api/conf/1.0/examples/LISAManager.get.json
It was missing the bulk payment breakdown, which was already being returned
from the Controller.
=> LISA-1792: Updated discover endpoint example response

app/uk/gov/hmrc/lisaapi/connectors/DesConnector.scala
In addition to the existing logging for a 200 response not being parsed correctly.
=> Log when a 201 response isn't parsed correctly

resources/public/api/conf/1.0/examples/LISATransaction.get.response.1.json, resources/public/api/conf/1.0/examples/LISATransaction.get.response.json, resources/public/api/conf/1.0/testdata/bonus-payment-get.md
The API's GET response only returns decimals where they are needed, so the documentation has now been updated to reflect this
For example the API would not return 1000.00 it would return 1000, similarly it would return 1000.5 instead of 1000.50
Only if there are two non-zero decimals would two decimal places be returned. i.e. 1000.99 would be returned as 1000.99
=> LISA-1934: Removed unneccesary decimal places from GET bonus request examples

app/uk/gov/hmrc/lisaapi/models/ReportWithdrawalChargeRequest.scala, app/uk/gov/hmrc/lisaapi/utils/WithdrawalChargeValidator.scala, resources/public/api/conf/1.0/schemas/WithdrawalCharge.post.schema.json, resources/public/api/conf/1.0/testdata/withdrawal-charge.md, test/unit/utils/WithdrawalChargeValidatorSpec.scala
Validation has been added to the automaticRecoveryAmount field to ensure it is never
greater than the withdrawalAmount.
=> LISA-2090: Added validation to Report Withdrawal Charge

resources/public/api/conf/2.0/examples/AnnualReturn.post.json, resources/public/api/conf/2.0/examples/AnnualReturnSuperseded.post.json, resources/public/api/conf/2.0/schemas/AnnualReturn.post.schema.json, resources/public/api/conf/2.0/testdata/annual-return.md
Added additional clarity on what is required for the lisaManagerName field.
Our User Research had identified this as a sticking point. It wasn't clear enough whether the user should provide the LISA provider's name (i.e. the company name), or the name of the individual responsible for managing that account.
=> Updated annual return API specification

resources/public/api/conf/2.0/testdata/withdrawal-charge.md
The account cancelled test scenario was incorrectly titled
as being an account closed scenario.
=> Typo fix for request withdrawal charge API spec

resources/public/api/conf/1.0/testdata/bonus-payment-get.md, resources/public/api/conf/1.0/testdata/bonus-payment.md, resources/public/api/conf/1.0/testdata/close-account.md, resources/public/api/conf/1.0/testdata/create-account.md, resources/public/api/conf/1.0/testdata/get-account.md, resources/public/api/conf/1.0/testdata/get-bulk-payment.md, resources/public/api/conf/1.0/testdata/get-investor-payment.md, resources/public/api/conf/1.0/testdata/life-event.md, resources/public/api/conf/1.0/testdata/lisa-create-investor.md, resources/public/api/conf/1.0/testdata/reinstate-account.md, resources/public/api/conf/1.0/testdata/subscription-update.md, resources/public/api/conf/2.0/testdata/annual-return.md, resources/public/api/conf/2.0/testdata/bonus-payment-get.md, resources/public/api/conf/2.0/testdata/bonus-payment.md, resources/public/api/conf/2.0/testdata/close-account.md, resources/public/api/conf/2.0/testdata/create-account.md, resources/public/api/conf/2.0/testdata/fund-release-extension.md, resources/public/api/conf/2.0/testdata/fund-release-outcome.md, resources/public/api/conf/2.0/testdata/fund-release.md, resources/public/api/conf/2.0/testdata/get-account.md, resources/public/api/conf/2.0/testdata/get-bulk-payment.md, resources/public/api/conf/2.0/testdata/get-investor-payment.md, resources/public/api/conf/2.0/testdata/life-event-get.md, resources/public/api/conf/2.0/testdata/life-event.md, resources/public/api/conf/2.0/testdata/lisa-create-investor.md, resources/public/api/conf/2.0/testdata/reinstate-account.md, resources/public/api/conf/2.0/testdata/subscription-update.md, resources/public/api/conf/2.0/testdata/withdrawal-charge-get.md, resources/public/api/conf/2.0/testdata/withdrawal-charge.md
They all used an absolute URL which specifically pointed to v1.0 of the API
spec. They have now all been replaced with a relative link for whichever
version of the spec the user is looking at.
=> Replaced the URL for every "use your test user profile" link.

resources/public/api/conf/1.0/application.raml
The payments and debts in a date range API only returns payments in version 1.0, so the heading was incorrect.
=> Rename an endpoint in version 1.0

resources/public/api/conf/1.0/application.raml
The endDate description for "Get a list of all payments in a date range" references periodStartDate, when it should reference startDate.
=> API documentation update for v1.0

app/uk/gov/hmrc/lisaapi/config/AppContext.scala, app/uk/gov/hmrc/lisaapi/controllers/APIVersioning.scala, app/uk/gov/hmrc/lisaapi/controllers/AnnualReturnController.scala, app/uk/gov/hmrc/lisaapi/controllers/Responses.scala, conf/application.conf, resources/public/api/conf/2.0/application.raml, test/unit/config/APIAccessConfigSpec.scala, test/unit/config/AppContextSpec.scala, test/unit/controllers/APIVersioningSpec.scala, test/unit/controllers/AnnualReturnControllerSpec.scala
It's now possible to disable this endpoint via config.
There is a "disabledEndpoints" list in the config, adding "annual-returns" to this will disable the endpoint and cause a NOT_IMPLEMENTED error to be returned to the user.
=> LISA-2403: Added feature flag to send an annual return API

build.sbt, conf/application.conf, project/AppDependencies.scala
A graphite-metrics import was causing the deployment to fail. This should fix it.
=> [RS][DDCE-1653] Fixing deployment issue.

project/AppDependencies.scala
The inclusion of auth-client 3.0.0 was causing a conflict in prod, making all requests to DES being unauthorised. Its removal will cause the auth-client to be pulled in from bootstrap-backend.
=> [RS][DDCE-1653] Removed old authclient.

app/uk/gov/hmrc/lisaapi/config/APIAccessConfig.scala, app/uk/gov/hmrc/lisaapi/controllers/Documentation.scala, app/uk/gov/hmrc/lisaapi/domain/APIAccess.scala, conf/application.conf, test/unit/config/APIAccessConfigSpec.scala, test/unit/domain/APIAccessSpec.scala
Checked all app-configs, the whitelistedApplicationIds wasn't overridden anywhere - possibly removed in the past?
=> [RS][DDCE-1812] Removed whitelist terminology.
